#
# Copyright 2016 SmartBear Software
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
#
package VericredClient::NetworksApi;

require 5.6.0;
use strict;
use warnings;
use utf8; 
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use VericredClient::ApiClient;
use VericredClient::Configuration;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class   = shift;
    my (%self) = (
        'api_client' => VericredClient::ApiClient->instance,
        @_
    );

    #my $self = {
    #    #api_client => $options->{api_client}
    #    api_client => $default_api_client
    #}; 

    bless \%self, $class;

}


#
# list_networks
#
# Networks
# 
# @param string $carrier_id Carrier HIOS Issuer ID (required)
{
    my $params = {
    'carrier_id' => {
        data_type => 'string',
        description => 'Carrier HIOS Issuer ID',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ list_networks } = { 
    	summary => 'Networks',
        params => $params,
        returns => 'NetworkSearchResponse',
        };
}
# @return NetworkSearchResponse
#
sub list_networks {
    my ($self, %args) = @_;

    # verify the required parameter 'carrier_id' is set
    unless (exists $args{'carrier_id'}) {
      croak("Missing the required parameter 'carrier_id' when calling list_networks");
    }

    # parse inputs
    my $_resource_path = '/networks';
    $_resource_path =~ s/{format}/json/; # default format to json

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # query params
    if ( exists $args{'carrier_id'}) {
        $query_params->{'carrier_id'} = $self->{api_client}->to_query_value($args{'carrier_id'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw()];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('NetworkSearchResponse', $response);
    return $_response_object;
}

1;
