#
# Copyright 2016 SmartBear Software
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
#
package VericredClient::ProvidersApi;

require 5.6.0;
use strict;
use warnings;
use utf8; 
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use VericredClient::ApiClient;
use VericredClient::Configuration;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class   = shift;
    my (%self) = (
        'api_client' => VericredClient::ApiClient->instance,
        @_
    );

    #my $self = {
    #    #api_client => $options->{api_client}
    #    api_client => $default_api_client
    #}; 

    bless \%self, $class;

}


#
# providers_get
#
# Find providers by term and zip code
# 
# @param string $search_term String to search by (required)
# @param string $zip_code Zip Code to search near (required)
# @param string $accepts_insurance Limit results to Providers who accept at least one insurance plan.  Note that the inverse of this filter is not supported and any value will evaluate to true (optional)
# @param ARRAY[string] $hios_ids HIOS id of one or more plans (optional)
# @param string $page Page number (optional)
# @param string $per_page Number of records to return per page (optional)
# @param string $radius Radius (in miles) to use to limit results (optional)
{
    my $params = {
    'search_term' => {
        data_type => 'string',
        description => 'String to search by',
        required => '1',
    },
    'zip_code' => {
        data_type => 'string',
        description => 'Zip Code to search near',
        required => '1',
    },
    'accepts_insurance' => {
        data_type => 'string',
        description => 'Limit results to Providers who accept at least one insurance plan.  Note that the inverse of this filter is not supported and any value will evaluate to true',
        required => '0',
    },
    'hios_ids' => {
        data_type => 'ARRAY[string]',
        description => 'HIOS id of one or more plans',
        required => '0',
    },
    'page' => {
        data_type => 'string',
        description => 'Page number',
        required => '0',
    },
    'per_page' => {
        data_type => 'string',
        description => 'Number of records to return per page',
        required => '0',
    },
    'radius' => {
        data_type => 'string',
        description => 'Radius (in miles) to use to limit results',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ providers_get } = { 
    	summary => 'Find providers by term and zip code',
        params => $params,
        returns => 'InlineResponse200',
        };
}
# @return InlineResponse200
#
sub providers_get {
    my ($self, %args) = @_;

    # verify the required parameter 'search_term' is set
    unless (exists $args{'search_term'}) {
      croak("Missing the required parameter 'search_term' when calling providers_get");
    }

    # verify the required parameter 'zip_code' is set
    unless (exists $args{'zip_code'}) {
      croak("Missing the required parameter 'zip_code' when calling providers_get");
    }

    # parse inputs
    my $_resource_path = '/providers';
    $_resource_path =~ s/{format}/json/; # default format to json

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept();
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'accepts_insurance'}) {
        $query_params->{'accepts_insurance'} = $self->{api_client}->to_query_value($args{'accepts_insurance'});
    }

    # query params
    if ( exists $args{'hios_ids'}) {
        $query_params->{'hios_ids'} = $self->{api_client}->to_query_value($args{'hios_ids'});
    }

    # query params
    if ( exists $args{'page'}) {
        $query_params->{'page'} = $self->{api_client}->to_query_value($args{'page'});
    }

    # query params
    if ( exists $args{'per_page'}) {
        $query_params->{'per_page'} = $self->{api_client}->to_query_value($args{'per_page'});
    }

    # query params
    if ( exists $args{'radius'}) {
        $query_params->{'radius'} = $self->{api_client}->to_query_value($args{'radius'});
    }

    # query params
    if ( exists $args{'search_term'}) {
        $query_params->{'search_term'} = $self->{api_client}->to_query_value($args{'search_term'});
    }

    # query params
    if ( exists $args{'zip_code'}) {
        $query_params->{'zip_code'} = $self->{api_client}->to_query_value($args{'zip_code'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw()];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('InlineResponse200', $response);
    return $_response_object;
}

#
# providers_npi_get
#
# Find a specific Provider
# 
# @param string $npi NPI number (required)
{
    my $params = {
    'npi' => {
        data_type => 'string',
        description => 'NPI number',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ providers_npi_get } = { 
    	summary => 'Find a specific Provider',
        params => $params,
        returns => 'InlineResponse2001',
        };
}
# @return InlineResponse2001
#
sub providers_npi_get {
    my ($self, %args) = @_;

    # verify the required parameter 'npi' is set
    unless (exists $args{'npi'}) {
      croak("Missing the required parameter 'npi' when calling providers_npi_get");
    }

    # parse inputs
    my $_resource_path = '/providers/{npi}';
    $_resource_path =~ s/{format}/json/; # default format to json

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept();
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'npi'}) {
        my $_base_variable = "{" . "npi" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'npi'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw()];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('InlineResponse2001', $response);
    return $_response_object;
}

1;
