package VericredClient::Object::County;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base ("Class::Accessor", "Class::Data::Inheritable");


#
#
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "VericredClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => '',
                                  class => 'County',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'id' => {
    	datatype => 'int',
    	base_name => 'id',
    	description => 'Primary key',
    	format => '',
    	read_only => '',
    		},
    'fips_code' => {
    	datatype => 'string',
    	base_name => 'fips_code',
    	description => 'State FIPS code',
    	format => '',
    	read_only => '',
    		},
    'name' => {
    	datatype => 'string',
    	base_name => 'name',
    	description => 'Human-readable name',
    	format => '',
    	read_only => '',
    		},
    'state_code' => {
    	datatype => 'string',
    	base_name => 'state_code',
    	description => 'Two-character state code',
    	format => '',
    	read_only => '',
    		},
    'state_id' => {
    	datatype => 'int',
    	base_name => 'state_id',
    	description => 'state relationship',
    	format => '',
    	read_only => '',
    		},
    'state_live' => {
    	datatype => 'boolean',
    	base_name => 'state_live',
    	description => 'Is the state containing this county active for consumers?
                  *deprecated in favor of last_date_for_individual',
    	format => '',
    	read_only => '',
    		},
    'state_live_for_business' => {
    	datatype => 'boolean',
    	base_name => 'state_live_for_business',
    	description => 'Is the state containing this county active for business?
                  *deprecated in favor of last_date_for_shop',
    	format => '',
    	read_only => '',
    		},
});

__PACKAGE__->swagger_types( {
    'id' => 'int',
    'fips_code' => 'string',
    'name' => 'string',
    'state_code' => 'string',
    'state_id' => 'int',
    'state_live' => 'boolean',
    'state_live_for_business' => 'boolean'
} );

__PACKAGE__->attribute_map( {
    'id' => 'id',
    'fips_code' => 'fips_code',
    'name' => 'name',
    'state_code' => 'state_code',
    'state_id' => 'state_id',
    'state_live' => 'state_live',
    'state_live_for_business' => 'state_live_for_business'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
