package VericredClient::Object::Pricing;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base ("Class::Accessor", "Class::Data::Inheritable");


#
#
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "VericredClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => '',
                                  class => 'Pricing',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'age' => {
    	datatype => 'int',
    	base_name => 'age',
    	description => 'Age of applicant',
    	format => '',
    	read_only => '',
    		},
    'effective_date' => {
    	datatype => 'DateTime',
    	base_name => 'effective_date',
    	description => 'Effective date of plan',
    	format => '',
    	read_only => '',
    		},
    'expiration_date' => {
    	datatype => 'DateTime',
    	base_name => 'expiration_date',
    	description => 'Plan expiration date',
    	format => '',
    	read_only => '',
    		},
    'plan_id' => {
    	datatype => 'int',
    	base_name => 'plan_id',
    	description => 'Foreign key to plans',
    	format => '',
    	read_only => '',
    		},
    'premium_child_only' => {
    	datatype => 'Number',
    	base_name => 'premium_child_only',
    	description => 'Child-only premium',
    	format => '',
    	read_only => '',
    		},
    'premium_family' => {
    	datatype => 'Number',
    	base_name => 'premium_family',
    	description => 'Family premium',
    	format => '',
    	read_only => '',
    		},
    'premium_single' => {
    	datatype => 'Number',
    	base_name => 'premium_single',
    	description => 'Single-person premium',
    	format => '',
    	read_only => '',
    		},
    'premium_single_and_children' => {
    	datatype => 'Number',
    	base_name => 'premium_single_and_children',
    	description => 'Single person including children premium',
    	format => '',
    	read_only => '',
    		},
    'premium_single_and_spouse' => {
    	datatype => 'Number',
    	base_name => 'premium_single_and_spouse',
    	description => 'Person with spouse premium',
    	format => '',
    	read_only => '',
    		},
    'premium_single_smoker' => {
    	datatype => 'Number',
    	base_name => 'premium_single_smoker',
    	description => 'Premium for single smoker',
    	format => '',
    	read_only => '',
    		},
    'rating_area_id' => {
    	datatype => 'string',
    	base_name => 'rating_area_id',
    	description => 'Foreign key to rating areas',
    	format => '',
    	read_only => '',
    		},
});

__PACKAGE__->swagger_types( {
    'age' => 'int',
    'effective_date' => 'DateTime',
    'expiration_date' => 'DateTime',
    'plan_id' => 'int',
    'premium_child_only' => 'Number',
    'premium_family' => 'Number',
    'premium_single' => 'Number',
    'premium_single_and_children' => 'Number',
    'premium_single_and_spouse' => 'Number',
    'premium_single_smoker' => 'Number',
    'rating_area_id' => 'string'
} );

__PACKAGE__->attribute_map( {
    'age' => 'age',
    'effective_date' => 'effective_date',
    'expiration_date' => 'expiration_date',
    'plan_id' => 'plan_id',
    'premium_child_only' => 'premium_child_only',
    'premium_family' => 'premium_family',
    'premium_single' => 'premium_single',
    'premium_single_and_children' => 'premium_single_and_children',
    'premium_single_and_spouse' => 'premium_single_and_spouse',
    'premium_single_smoker' => 'premium_single_smoker',
    'rating_area_id' => 'rating_area_id'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
