=begin comment

Vericred API

Vericred's API allows you to search for Health Plans that a specific doctor
accepts.

## Getting Started

Visit our [Developer Portal](https://vericred.3scale.net) to
create an account.

Once you have created an account, you can create one Application for
Production and another for our Sandbox (select the appropriate Plan when
you create the Application).

## Authentication

To authenticate, pass the API Key you created in the Developer Portal as
a `Vericred-Api-Key` header.

`curl -H 'Vericred-Api-Key: YOUR_KEY' "https://api.vericred.com/providers?search_term=Foo&zip_code=11215"`

## Versioning

Vericred's API default to the latest version.  However, if you need a specific
version, you can request it with an `Accept-Version` header.

The current version is `v3`.  Previous versions are `v1` and `v2`.

`curl -H 'Vericred-Api-Key: YOUR_KEY' -H 'Accept-Version: v2' "https://api.vericred.com/providers?search_term=Foo&zip_code=11215"`

## Pagination

Endpoints that accept `page` and `per_page` parameters are paginated. They expose
four additional fields that contain data about your position in the response,
namely `Total`, `Per-Page`, `Link`, and `Page` as described in [RFC-5988](https://tools.ietf.org/html/rfc5988).

For example, to display 5 results per page and view the second page of a
`GET` to `/networks`, your final request would be `GET /networks?....page=2&per_page=5`.

## Sideloading

When we return multiple levels of an object graph (e.g. `Provider`s and their `State`s
we sideload the associated data.  In this example, we would provide an Array of
`State`s and a `state_id` for each provider.  This is done primarily to reduce the
payload size since many of the `Provider`s will share a `State`

```
{
  providers: [{ id: 1, state_id: 1}, { id: 2, state_id: 1 }],
  states: [{ id: 1, code: 'NY' }]
}
```

If you need the second level of the object graph, you can just match the
corresponding id.

## Selecting specific data

All endpoints allow you to specify which fields you would like to return.
This allows you to limit the response to contain only the data you need.

For example, let's take a request that returns the following JSON by default

```
{
  provider: {
    id: 1,
    name: 'John',
    phone: '1234567890',
    field_we_dont_care_about: 'value_we_dont_care_about'
  },
  states: [{
    id: 1,
    name: 'New York',
    code: 'NY',
    field_we_dont_care_about: 'value_we_dont_care_about'
  }]
}
```

To limit our results to only return the fields we care about, we specify the
`select` query string parameter for the corresponding fields in the JSON
document.

In this case, we want to select `name` and `phone` from the `provider` key,
so we would add the parameters `select=provider.name,provider.phone`.
We also want the `name` and `code` from the `states` key, so we would
add the parameters `select=states.name,staes.code`.  The id field of
each document is always returned whether or not it is requested.

Our final request would be `GET /providers/12345?select=provider.name,provider.phone,states.name,states.code`

The response would be

```
{
  provider: {
    id: 1,
    name: 'John',
    phone: '1234567890'
  },
  states: [{
    id: 1,
    name: 'New York',
    code: 'NY'
  }]
}
```



OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package VericredClient::Object::ProviderDetails;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base ("Class::Accessor", "Class::Data::Inheritable");


#
#
#
# NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
# REF: https://github.com/swagger-api/swagger-codegen
#

=begin comment

Vericred API

Vericred's API allows you to search for Health Plans that a specific doctor
accepts.

## Getting Started

Visit our [Developer Portal](https://vericred.3scale.net) to
create an account.

Once you have created an account, you can create one Application for
Production and another for our Sandbox (select the appropriate Plan when
you create the Application).

## Authentication

To authenticate, pass the API Key you created in the Developer Portal as
a `Vericred-Api-Key` header.

`curl -H 'Vericred-Api-Key: YOUR_KEY' "https://api.vericred.com/providers?search_term=Foo&zip_code=11215"`

## Versioning

Vericred's API default to the latest version.  However, if you need a specific
version, you can request it with an `Accept-Version` header.

The current version is `v3`.  Previous versions are `v1` and `v2`.

`curl -H 'Vericred-Api-Key: YOUR_KEY' -H 'Accept-Version: v2' "https://api.vericred.com/providers?search_term=Foo&zip_code=11215"`

## Pagination

Endpoints that accept `page` and `per_page` parameters are paginated. They expose
four additional fields that contain data about your position in the response,
namely `Total`, `Per-Page`, `Link`, and `Page` as described in [RFC-5988](https://tools.ietf.org/html/rfc5988).

For example, to display 5 results per page and view the second page of a
`GET` to `/networks`, your final request would be `GET /networks?....page=2&per_page=5`.

## Sideloading

When we return multiple levels of an object graph (e.g. `Provider`s and their `State`s
we sideload the associated data.  In this example, we would provide an Array of
`State`s and a `state_id` for each provider.  This is done primarily to reduce the
payload size since many of the `Provider`s will share a `State`

```
{
  providers: [{ id: 1, state_id: 1}, { id: 2, state_id: 1 }],
  states: [{ id: 1, code: 'NY' }]
}
```

If you need the second level of the object graph, you can just match the
corresponding id.

## Selecting specific data

All endpoints allow you to specify which fields you would like to return.
This allows you to limit the response to contain only the data you need.

For example, let's take a request that returns the following JSON by default

```
{
  provider: {
    id: 1,
    name: 'John',
    phone: '1234567890',
    field_we_dont_care_about: 'value_we_dont_care_about'
  },
  states: [{
    id: 1,
    name: 'New York',
    code: 'NY',
    field_we_dont_care_about: 'value_we_dont_care_about'
  }]
}
```

To limit our results to only return the fields we care about, we specify the
`select` query string parameter for the corresponding fields in the JSON
document.

In this case, we want to select `name` and `phone` from the `provider` key,
so we would add the parameters `select=provider.name,provider.phone`.
We also want the `name` and `code` from the `states` key, so we would
add the parameters `select=states.name,staes.code`.  The id field of
each document is always returned whether or not it is requested.

Our final request would be `GET /providers/12345?select=provider.name,provider.phone,states.name,states.code`

The response would be

```
{
  provider: {
    id: 1,
    name: 'John',
    phone: '1234567890'
  },
  states: [{
    id: 1,
    name: 'New York',
    code: 'NY'
  }]
}
```



OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "VericredClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => '',
                                  class => 'ProviderDetails',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'accepting_change_of_payor_patients' => {
    	datatype => 'boolean',
    	base_name => 'accepting_change_of_payor_patients',
    	description => 'Is this provider accepting patients with a change of insurance?',
    	format => '',
    	read_only => '',
    		},
    'accepting_medicaid_patients' => {
    	datatype => 'boolean',
    	base_name => 'accepting_medicaid_patients',
    	description => 'Is this provider accepting new Medicaid patients?',
    	format => '',
    	read_only => '',
    		},
    'accepting_medicare_patients' => {
    	datatype => 'boolean',
    	base_name => 'accepting_medicare_patients',
    	description => 'Is this provider accepting new Medicare patients?',
    	format => '',
    	read_only => '',
    		},
    'accepting_private_patients' => {
    	datatype => 'boolean',
    	base_name => 'accepting_private_patients',
    	description => 'Is this provider accepting new patients with private insurance?',
    	format => '',
    	read_only => '',
    		},
    'accepting_referral_patients' => {
    	datatype => 'boolean',
    	base_name => 'accepting_referral_patients',
    	description => 'Is this provider accepting new patients via referrals?',
    	format => '',
    	read_only => '',
    		},
    'city' => {
    	datatype => 'string',
    	base_name => 'city',
    	description => 'City name (e.g. Springfield).',
    	format => '',
    	read_only => '',
    		},
    'email' => {
    	datatype => 'string',
    	base_name => 'email',
    	description => 'Primary email address to contact the provider.',
    	format => '',
    	read_only => '',
    		},
    'gender' => {
    	datatype => 'string',
    	base_name => 'gender',
    	description => 'Provider&#39;s gender (M or F)',
    	format => '',
    	read_only => '',
    		},
    'first_name' => {
    	datatype => 'string',
    	base_name => 'first_name',
    	description => 'Given name for the provider.',
    	format => '',
    	read_only => '',
    		},
    'id' => {
    	datatype => 'int',
    	base_name => 'id',
    	description => 'National Provider Index (NPI) number',
    	format => '',
    	read_only => '',
    		},
    'last_name' => {
    	datatype => 'string',
    	base_name => 'last_name',
    	description => 'Family name for the provider.',
    	format => '',
    	read_only => '',
    		},
    'latitude' => {
    	datatype => 'Number',
    	base_name => 'latitude',
    	description => 'Latitude of provider',
    	format => '',
    	read_only => '',
    		},
    'longitude' => {
    	datatype => 'Number',
    	base_name => 'longitude',
    	description => 'Longitude of provider',
    	format => '',
    	read_only => '',
    		},
    'middle_name' => {
    	datatype => 'string',
    	base_name => 'middle_name',
    	description => 'Middle name for the provider.',
    	format => '',
    	read_only => '',
    		},
    'network_ids' => {
    	datatype => 'ARRAY[int]',
    	base_name => 'network_ids',
    	description => 'Array of network ids',
    	format => '',
    	read_only => '',
    		},
    'organization_name' => {
    	datatype => 'string',
    	base_name => 'organization_name',
    	description => 'name for the providers of type: organization.',
    	format => '',
    	read_only => '',
    		},
    'personal_phone' => {
    	datatype => 'string',
    	base_name => 'personal_phone',
    	description => 'Personal contact phone for the provider.',
    	format => '',
    	read_only => '',
    		},
    'phone' => {
    	datatype => 'string',
    	base_name => 'phone',
    	description => 'Office phone for the provider',
    	format => '',
    	read_only => '',
    		},
    'presentation_name' => {
    	datatype => 'string',
    	base_name => 'presentation_name',
    	description => 'Preferred name for display (e.g. Dr. Francis White may prefer Dr. Frank White)',
    	format => '',
    	read_only => '',
    		},
    'specialty' => {
    	datatype => 'string',
    	base_name => 'specialty',
    	description => 'Name of the primary Specialty',
    	format => '',
    	read_only => '',
    		},
    'state' => {
    	datatype => 'string',
    	base_name => 'state',
    	description => 'State code for the provider&#39;s address (e.g. NY).',
    	format => '',
    	read_only => '',
    		},
    'state_id' => {
    	datatype => 'int',
    	base_name => 'state_id',
    	description => 'Foreign key to States',
    	format => '',
    	read_only => '',
    		},
    'street_line_1' => {
    	datatype => 'string',
    	base_name => 'street_line_1',
    	description => 'First line of the provider&#39;s street address.',
    	format => '',
    	read_only => '',
    		},
    'street_line_2' => {
    	datatype => 'string',
    	base_name => 'street_line_2',
    	description => 'Second line of the provider&#39;s street address.',
    	format => '',
    	read_only => '',
    		},
    'suffix' => {
    	datatype => 'string',
    	base_name => 'suffix',
    	description => 'Suffix for the provider&#39;s name (e.g. Jr)',
    	format => '',
    	read_only => '',
    		},
    'title' => {
    	datatype => 'string',
    	base_name => 'title',
    	description => 'Professional title for the provider (e.g. Dr).',
    	format => '',
    	read_only => '',
    		},
    'type' => {
    	datatype => 'string',
    	base_name => 'type',
    	description => 'Type of NPI number (individual provider vs organization).',
    	format => '',
    	read_only => '',
    		},
    'zip_code' => {
    	datatype => 'string',
    	base_name => 'zip_code',
    	description => 'Postal code for the provider&#39;s address (e.g. 11215)',
    	format => '',
    	read_only => '',
    		},
    'hios_ids' => {
    	datatype => 'ARRAY[string]',
    	base_name => 'hios_ids',
    	description => 'List of HIOS ids for this provider',
    	format => '',
    	read_only => '',
    		},
});

__PACKAGE__->swagger_types( {
    'accepting_change_of_payor_patients' => 'boolean',
    'accepting_medicaid_patients' => 'boolean',
    'accepting_medicare_patients' => 'boolean',
    'accepting_private_patients' => 'boolean',
    'accepting_referral_patients' => 'boolean',
    'city' => 'string',
    'email' => 'string',
    'gender' => 'string',
    'first_name' => 'string',
    'id' => 'int',
    'last_name' => 'string',
    'latitude' => 'Number',
    'longitude' => 'Number',
    'middle_name' => 'string',
    'network_ids' => 'ARRAY[int]',
    'organization_name' => 'string',
    'personal_phone' => 'string',
    'phone' => 'string',
    'presentation_name' => 'string',
    'specialty' => 'string',
    'state' => 'string',
    'state_id' => 'int',
    'street_line_1' => 'string',
    'street_line_2' => 'string',
    'suffix' => 'string',
    'title' => 'string',
    'type' => 'string',
    'zip_code' => 'string',
    'hios_ids' => 'ARRAY[string]'
} );

__PACKAGE__->attribute_map( {
    'accepting_change_of_payor_patients' => 'accepting_change_of_payor_patients',
    'accepting_medicaid_patients' => 'accepting_medicaid_patients',
    'accepting_medicare_patients' => 'accepting_medicare_patients',
    'accepting_private_patients' => 'accepting_private_patients',
    'accepting_referral_patients' => 'accepting_referral_patients',
    'city' => 'city',
    'email' => 'email',
    'gender' => 'gender',
    'first_name' => 'first_name',
    'id' => 'id',
    'last_name' => 'last_name',
    'latitude' => 'latitude',
    'longitude' => 'longitude',
    'middle_name' => 'middle_name',
    'network_ids' => 'network_ids',
    'organization_name' => 'organization_name',
    'personal_phone' => 'personal_phone',
    'phone' => 'phone',
    'presentation_name' => 'presentation_name',
    'specialty' => 'specialty',
    'state' => 'state',
    'state_id' => 'state_id',
    'street_line_1' => 'street_line_1',
    'street_line_2' => 'street_line_2',
    'suffix' => 'suffix',
    'title' => 'title',
    'type' => 'type',
    'zip_code' => 'zip_code',
    'hios_ids' => 'hios_ids'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
