package VericredClient::Object::RequestProvidersSearch;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base ("Class::Accessor", "Class::Data::Inheritable");


#
#
#
#NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
#

__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "VericredClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => '',
                                  class => 'RequestProvidersSearch',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'accepts_insurance' => {
    	datatype => 'boolean',
    	base_name => 'accepts_insurance',
    	description => 'Limit results to Providers who accept at least one insurance
        plan.  Note that the inverse of this filter is not supported and
        any value will evaluate to true',
    	format => '',
    	read_only => '',
    		},
    'hios_ids' => {
    	datatype => 'ARRAY[string]',
    	base_name => 'hios_ids',
    	description => 'List of HIOS ids',
    	format => '',
    	read_only => '',
    		},
    'page' => {
    	datatype => 'int',
    	base_name => 'page',
    	description => 'Page number',
    	format => '',
    	read_only => '',
    		},
    'per_page' => {
    	datatype => 'int',
    	base_name => 'per_page',
    	description => 'Number of records to return per page',
    	format => '',
    	read_only => '',
    		},
    'radius' => {
    	datatype => 'int',
    	base_name => 'radius',
    	description => 'Radius (in miles) to use to limit results',
    	format => '',
    	read_only => '',
    		},
    'search_term' => {
    	datatype => 'string',
    	base_name => 'search_term',
    	description => 'String to search by',
    	format => '',
    	read_only => '',
    		},
    'zip_code' => {
    	datatype => 'string',
    	base_name => 'zip_code',
    	description => 'Zip Code to search near',
    	format => '',
    	read_only => '',
    		},
    'type' => {
    	datatype => 'string',
    	base_name => 'type',
    	description => 'Either organization or individual',
    	format => '',
    	read_only => '',
    		},
});

__PACKAGE__->swagger_types( {
    'accepts_insurance' => 'boolean',
    'hios_ids' => 'ARRAY[string]',
    'page' => 'int',
    'per_page' => 'int',
    'radius' => 'int',
    'search_term' => 'string',
    'zip_code' => 'string',
    'type' => 'string'
} );

__PACKAGE__->attribute_map( {
    'accepts_insurance' => 'accepts_insurance',
    'hios_ids' => 'hios_ids',
    'page' => 'page',
    'per_page' => 'per_page',
    'radius' => 'radius',
    'search_term' => 'search_term',
    'zip_code' => 'zip_code',
    'type' => 'type'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
