#
# Copyright 2016 SmartBear Software
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test case below to test the API endpoints.
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('VericredClient::DrugsApi');

my $api = VericredClient::DrugsApi->new();
isa_ok($api, 'VericredClient::DrugsApi');

#
# get_drug_coverages test
#
{
    my $ndc_package_code = undef; # replace NULL with a proper value
    my $audience = undef; # replace NULL with a proper value
    my $state_code = undef; # replace NULL with a proper value
    my $vericred_api_key = undef; # replace NULL with a proper value
    my $result = $api->get_drug_coverages(ndc_package_code => $ndc_package_code, audience => $audience, state_code => $state_code, vericred_api_key => $vericred_api_key);
}

#
# list_drugs test
#
{
    my $search_term = undef; # replace NULL with a proper value
    my $vericred_api_key = undef; # replace NULL with a proper value
    my $result = $api->list_drugs(search_term => $search_term, vericred_api_key => $vericred_api_key);
}


1;
