#
# Copyright 2016 SmartBear Software
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test case below to test the API endpoints.
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('VericredClient::ProvidersApi');

my $api = VericredClient::ProvidersApi->new();
isa_ok($api, 'VericredClient::ProvidersApi');

#
# providers_get test
#
{
    my $search_term = undef; # replace NULL with a proper value
    my $zip_code = undef; # replace NULL with a proper value
    my $accepts_insurance = undef; # replace NULL with a proper value
    my $hios_ids = undef; # replace NULL with a proper value
    my $page = undef; # replace NULL with a proper value
    my $per_page = undef; # replace NULL with a proper value
    my $radius = undef; # replace NULL with a proper value
    my $result = $api->providers_get(search_term => $search_term, zip_code => $zip_code, accepts_insurance => $accepts_insurance, hios_ids => $hios_ids, page => $page, per_page => $per_page, radius => $radius);
}

#
# providers_npi_get test
#
{
    my $npi = undef; # replace NULL with a proper value
    my $result = $api->providers_npi_get(npi => $npi);
}


1;
